## Day 28 Lecture 2 Assignment

In this assignment, we will learn about overfitting and regularization. We will use the king county housing dataset loaded below and analyze the regression from this dataset.

In [1]:
%matplotlib inline

import math

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import ds_useful

[My Useful Data Science Functions](https://github.com/cobyoram/python-for-data-scientists/blob/master/ds_useful.py)

In [13]:
data = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/kc_house_data.csv')

In [19]:
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

Perform the same transformations in the previous assignment to meet model assumptions:
1. Transform price and sqft_living by applying the natual log
2. Remove all columns except: log price, bedrooms, bathrooms, log_sqft_living, floors, waterfront
3. Split the data into train and test subsets. 20% of the data should be in the test subset

In [20]:
# answer below:
king_county = data.copy()
king_county = king_county.assign(log_sqft_living=np.log(king_county['sqft_living']))
king_county = king_county.assign(log_price=np.log(king_county['price']))

In [21]:
include_cols = ['log_price', 'bedrooms', 'bathrooms', 'log_sqft_living', 'floors', 'waterfront']
king_county = king_county[include_cols]

In [22]:
from sklearn.model_selection import train_test_split

Y = king_county['log_price']
X = king_county.drop('log_price', axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .2)

Apply a ridge regression model with lambda=50 to the data and evaluate by looking at r squared for test and train

In [25]:
# answer below:
from sklearn import linear_model as lm

ridgereg = lm.Ridge(alpha=50)
ridgereg.fit(X_train, Y_train)



print('R-squared of the model on the training set is: {}'.format(ridgereg.score(X_train, Y_train)))
print('----------Test set statistics------------')
print('R-squared of the model on the test set is: {}'.format(ridgereg.score(X_test, Y_test)))

R-squared of the model on the training set is: 0.48470265888789565
----------Test set statistics------------
R-squared of the model on the test set is: 0.47226311956265765

Perform a grid search for the following values of alpha: 1, 5, 10, 100, 500, 1000, 10000 to find the most optimal ridge regression model.

In [27]:
#answer below:
from sklearn.model_selection import GridSearchCV

tuned_parameters = [{'alpha': [1, 5, 10, 100, 500, 1000, 10000]}]

clf = GridSearchCV(ridgereg, param_grid=tuned_parameters)
clf.fit(X_train, Y_train)

print(clf.best_score_)
print(clf.best_estimator_.alpha)

0.4851578437875016
1