### Practice - Python for data scientists III - pandas - SOLUTION

Pandas is a package built on top of NumPy, and provides an efficient implementation of a `DataFrame`.

Answer each **Question**

`DataFrames` are essentially multidimensional arrays with row and column labels, and often with heterogeneous types and missing data.

In addition to providing storage interface for labeled data, Pandas implements a number of  data operations similar to operations provided by database frameworks and spreadsheet programs.

NumPy's ``ndarray`` data structure provides features for the type of clean, well-organized data typically seen in numerical computing tasks. While it serves this purpose well, its limitations become clear when we need more flexibility, e.g., attaching labels to data, working with missing data, etc. NumPy operations that do not map well to element-wise broadcasting, e.g., groupings, pivots, etc., each of which is an important piece of analyzing less structured data available.

Pandas ``Series`` and ``DataFrame`` objects build on the NumPy array structure and provide efficient access to these sorts of "data munging" tasks that occupy much of a data scientist's time.

References:  
http://pandas.pydata.org/  
http://pandas.pydata.org/pandas-docs/stable/10min.html   
https://jakevdp.github.io/PythonDataScienceHandbook/   
http://shop.oreilly.com/product/0636920033400.do

#### Data structures

- Series  
- Dataframe

Quick overview of the fundamental data structures in Pandas:   
- The fundamental behavior about data types, indexing, and axis labeling / alignment apply across all of the objects.  
- Maintaining an intrinsic link between labels and data.

#### Series data structure

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). 

The axis labels are collectively referred to as the index.

Can create data from:
- a Python dict  
- an ndarray  
- a scalar value

#### Standard imports

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.__version__

In [0]:
pd.crosstab?

#### Pandas Series object

A series can be creted from a list, array, dictionary, etc.

Creating a series from an ndarray

In [0]:
np.random.randn?

In [0]:
# index must be same length as data
data = np.random.randn(5)
index = ['a', 'b', 'c', 'd', 'e']
s = pd.Series(data, index=index)
s

The Series wraps both a sequence of values and a sequence of indices, which can accessed with the `values` and `index` attributes. The values are a familiar NumPy array.

In [0]:
print(s.values)
print(s.index)

Creating a series from a list

In [0]:
# index must be same length as data
data = [1,2,3,4,5]
index = ['a', 'b', 'c', 'd', 'e']
r = pd.Series(data, index=index)
r

*Note: Pandas allows duplicate index keys (for performance reasons)*

If an index is not provided, one will be created.

In [0]:
# index must be same length as data
data = [1,2,3,4,5]
r = pd.Series(data)
r

From dict

If no index is provided, the labels will be used and placed in the order of the dict.

In [0]:
d = {'b' : 1, 'a' : 0, 'c' : 2}
pd.Series(d)

From scalar

An index is require for scalar data.

In [0]:
pd.Series(5., index=['a', 'b', 'c', 'd', 'e'])

Series are similar to NumPy ndarray and can be accessed using indexing `[]`,

In [0]:
s.iloc[1]

In [0]:
s['a']

In [0]:
s[:-3]

In [0]:
s.iloc[0]

Implicit indexing versus explicit indexing

In [0]:
r.index = [1,2,3,4,5]
r

In [0]:
r[1]

In [0]:
r.loc[1]

In [0]:
r.iloc[0]

Filter / mask selection

In [0]:
s > s.median()

In [0]:
s[s > s.median()]

In [0]:
s[[4, 3, 1]]

In [0]:
s[[4]]

Series are also dict-like.

A Series is like a fixed-size `dict` in that you can get and set values by index label:

In [0]:
s['a']

In [0]:
s['e'] = 12.
s

In [0]:
'e' in s

In [0]:
'f' in s

In [0]:
s.get('f')

In [0]:
s.get('f', np.nan)

#### Vectorized operations

Like numpy, you can use vectorized operations.

In [0]:
s

In [0]:
s+s

In [0]:
s*2

In [0]:
s.sum(axis=0)

A key difference between Series and ndarray is that operations between Series automatically align the data based on label. 

So you can write computations without giving consideration to whether the Series involved have the same labels.

In [0]:
s

In [0]:
s[1:]

In [0]:
s[:-1]

The result of an operation between unaligned Series will have the union of the indexes involved.

In [0]:
s[1:] + s[:-1]

#### Name attribute

In [0]:
s = pd.Series(np.random.randn(5), name='Mel')
s

In [0]:
s.name

#### Querying a Series

In [0]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [0]:
s.iloc[3]

In [0]:
s.loc['Golf']

#### Series performance

Create a large series to evaluate performance

In [0]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

In [0]:
len(s)

In [0]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

In [0]:
%%timeit -n 100
summary = np.sum(s)

In [0]:
s+=2
s.head()

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,100,1000))
for label, value in s.iteritems():
    s.loc[label]= value+2

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,100,1000))
s+=2

#### Dataframe

DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. 

Similar to a database table, a spreadsheet, or a dict of Series objects. 

DataFrame accepts many different kinds of input:

- Dict of 1D ndarrays, lists, dicts, or Series  
- 2-D numpy.ndarray  
- Structured or record ndarray  
- A Series 
- Another DataFrame

DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names.

So a DataFrame as a sequence of aligned Series objects. E.g., a series of dictionaries.

Construct new Series for population and area as disctionaries.

In [0]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

In [0]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [0]:
population_only = pd.DataFrame({'population': population})
population_only

In [0]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [0]:
states.index

Additionally, the DataFrame has a columns attribute, which is an Index object holding the column labels:

In [0]:
states.columns

Another example of a dataframe from dict of Series

In [0]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
    'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
d

In [0]:
pd.DataFrame(d, index=['d', 'b', 'a'])

In [0]:
pd.DataFrame(d, index=['d', 'b', 'a'], columns=['two', 'three'])

The row and column labels can be accessed using the index and columns attributes:

In [0]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
    'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

In [0]:
df.columns

In [0]:
df['one']

In [0]:
df.loc[['a']]

In [0]:
print( type(df.loc['a']))
print( type(df.loc[['a']]))

Dataframe from dict of ndarrays or lists

In [0]:
d = {'one' : [1., 2., 3., 4.],    
     'two' : [4., 3., 2., 1.]}

In [0]:
pd.DataFrame(d)

DataFrame from a list of dicts

In [0]:
data2 = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
pd.DataFrame(data2)

In [0]:
pd.DataFrame(data2, index=['first', 'second'])

#### Column selection, addition, deletion

Similar to a dict of like-indexed Series objects.

In [0]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)
all_countries

In [0]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Jay',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kim',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Sergey',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], 
                  index=['Store 1', 'Store 1', 'Store 2'])
df.head()

In [0]:
df.loc['Store 2']

In [0]:
type( df.loc['Store 2'] )

In [0]:
df.loc['Store 1','Cost']

In [0]:
type( df.loc['Store 1','Cost'] )

In [0]:
df.T

In [0]:
df.T.loc['Cost']

In [0]:
df.loc['Store 1']['Cost']

Beware of the shallow copy

In [0]:
df

In [0]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

In [0]:
copy_df.drop?

In [0]:
del copy_df['Name']
copy_df

In [0]:
df['Location'] = None
df

#### Dataframe Indexing and Loading

In [0]:
costs = df['Cost']
costs

In [0]:
costs+=2
costs

In [0]:
df

Inspect olympic data file

In [0]:
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/olympics.csv')
df.head()

Deal with header row and index column

In [0]:
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/olympics.csv', index_col = 0, skiprows=1)
df.head()

In [0]:
df.columns

Clean up the header

In [0]:
for col in df.columns:
    print(col)
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head(20)

#### Querying a DataFrame

In [0]:
# Which countries have received gold medals?
df['Gold'] > 0

In [0]:
# Use binary mask to restrict results
only_gold = df.where(df['Gold'] > 0)
only_gold.head(10)

In [0]:
only_gold = only_gold.dropna()
only_gold.head()

In [0]:
df['Gold'].count()

Slightly more comlex binary mask

#### Question

Winter Gold 'Gold.1' and no summer 'Gold'

In [0]:
# Your work here

#### Indexing dataframes

In [0]:
df.head()

In [0]:
df['country'] = df.index
df = df.set_index('Gold')
df.head()

In [0]:
df = df.reset_index()
df.head()

#### Question:

Provide a list of countries who have received silver or bronze, but never gold medals in the summer olympics.

In [0]:
# Your work here

In [0]:
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/census.csv')
df.head()

In [0]:
df['SUMLEV'].unique()

In [0]:
df=df[df['SUMLEV'] == 50]
df.head()

In [0]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

In [0]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

In [0]:
df.loc['Michigan', 'Washtenaw County']

In [0]:
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

#### Missing values

In [0]:
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/log.csv')
df

In [0]:
df.fillna?

In [0]:
df = df.set_index('time')
df = df.sort_index()
df

In [0]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

In [0]:
df = df.fillna(method='ffill')
df.head()

In [0]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)

In [0]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

In [0]:
total = 0
for item in s:
    total+=item
print(total)

In [0]:
import numpy as np

total = np.sum(s)
print(total)

In [0]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

In [0]:
len(s)

In [0]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

In [0]:
%%timeit -n 100
summary = np.sum(s)

In [0]:
s+=2 #adds two to each item in s using broadcasting
s.head()

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

In [0]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

In [0]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [0]:
original_sports

In [0]:
cricket_loving_countries

In [0]:
all_countries

In [0]:
#### Question

From all_countries, list 'Cricket' loving countries.

In [0]:
# Your answer here